# Generated by Django 3.0.8 on 2022-05-15 11:55

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20220515_1547'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_nature', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time')], default='Part Time', max_length=20)),
                ('Salary', models.CharField(blank=True, max_length=255, null=True)),
                ('vacancy', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('published_on', models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 17, 55, 32, 7994))),
                ('Date_Line', models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 17, 55, 32, 7994))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.job_provider_profile')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
