# Generated by Django 3.0.8 on 2022-05-15 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0002_auto_20220515_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Date_Line',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 21, 28, 50, 101655)),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='published_on',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 21, 28, 50, 101655)),
        ),
    ]
