# Generated by Django 3.0.8 on 2022-05-15 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0003_auto_20220515_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='Keywords',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='Date_Line',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 22, 43, 14, 38785)),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='published_on',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 15, 22, 43, 14, 38785)),
        ),
    ]
