# Generated by Django 3.0.8 on 2022-05-16 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_job_seeker_profile_designation'),
        ('job_posts', '0009_auto_20220516_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='Date_Line',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 16, 23, 32, 58, 647921)),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='published_on',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 5, 16, 23, 32, 58, 647921)),
        ),
        migrations.CreateModel(
            name='Job_Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Portfolio_website', models.CharField(blank=True, max_length=255, null=True)),
                ('Attach_File', models.FileField(blank=True, null=True, upload_to='Job_apply/File/')),
                ('Cover_Letter', models.TextField(blank=True, null=True)),
                ('Apply_Time', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 16, 23, 32, 58, 648920))),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_posts.Jobs')),
                ('Job_Seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.job_seeker_profile')),
            ],
        ),
    ]
