# Generated by Django 3.0.8 on 2022-05-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job_provider_profile',
            options={'verbose_name_plural': 'Job Provider Profile'},
        ),
        migrations.AlterField(
            model_name='job_provider_profile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='job_provider/company_logo/'),
        ),
    ]
