# Generated by Django 3.0.8 on 2022-05-15 17:44

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20220515_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_seeker_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.CharField(blank=True, max_length=255, null=True)),
                ('Skill', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Qualification', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Resume', models.FileField(blank=True, null=True, upload_to='job_seeker/resume/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Job Seeker Profile',
            },
        ),
    ]
