# Generated by Django 3.0.8 on 2022-05-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_job_seeker_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker_profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='job_seeker/image/'),
        ),
    ]
