# Generated by Django 3.0.8 on 2022-05-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_job_seeker_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_seeker_profile',
            old_name='image',
            new_name='Your_image',
        ),
    ]
