# Generated by Django 3.0.8 on 2022-05-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_job_seeker_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker_profile',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
