# Generated by Django 3.0.8 on 2022-05-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('', ''), ('Admin', 'Admin'), ('Job Seeker', 'Job Seeker'), ('Job Provider', 'Job Provider')], default='', max_length=20),
        ),
    ]
