# Generated by Django 3.0.8 on 2022-05-15 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220515_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter_table',
            options={'verbose_name_plural': 'Newsletter Table'},
        ),
        migrations.AlterField(
            model_name='contact_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 15, 22, 43, 14, 20210)),
        ),
        migrations.AlterField(
            model_name='newsletter_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 15, 22, 43, 14, 21208)),
        ),
    ]
