# Generated by Django 3.0.8 on 2022-05-18 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220517_0002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Table',
        ),
        migrations.AlterField(
            model_name='newsletter_table',
            name='Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 18, 21, 50, 47, 775093)),
        ),
    ]
